In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.10.0'

In [3]:
hello = tf.constant("Hello world!")
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world!'>

In [4]:
hello = tf.constant("Hello World!")
const_scalar = tf.constant(7)
const_matrix = tf.constant([[1,2], [3,4]])
mat_fill = tf.fill((4,4), 9)                                # A 4x4 tensor filled with 9s.
mat_zeros = tf.zeros((3,3))                                 # A 3x3 tensor filled with 0s.
mat_ones = tf.ones((5,5))
mat_randn = tf.random.normal((3,3), mean=0, stddev=1.0)
mat_randu = tf.random.uniform((4,4), minval=0, maxval=1.0)


In [5]:
my_ops=[hello, const_scalar, const_matrix, mat_fill, mat_zeros, mat_ones, mat_randn, mat_randu]
for op in my_ops:
    print(type(op))
    print('\n')
    print(op)
    print('\n')

<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(b'Hello World!', shape=(), dtype=string)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(7, shape=(), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(4, 4), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[-1.0070502  -1.0932822  -0.34068474]
 [ 0.77683175 -1.5501325  -1.4521161 ]
 [-0.64146495  0.9967608   0.33802506]], shape=(3, 3), dtype=float32)




In [6]:
n1 = tf.constant(3)
n2 = tf.constant(2)
n3 = n1*n2
print(n3)

tf.Tensor(6, shape=(), dtype=int32)


In [8]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.add(n1, n2)
print(n3)

tf.Tensor(9, shape=(), dtype=int32)


In [9]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.multiply(n1,n2)
print(n3)

tf.Tensor(20, shape=(), dtype=int32)


In [10]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.pow(n1,n2)
print(n3)

tf.Tensor(8, shape=(), dtype=int32)


In [12]:
n1 = tf.constant([[1,2], [3,4]])
n2 = tf.constant([[5,6], [7,8]])
m3 = tf.matmul(n1, n2)
print(m3)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [14]:
m3 = tf.multiply(n1, n2)
print(m3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [15]:
# Matrix functions.
m = tf.constant([[1.0,2.0],[3.0,4.0]])
m_diagonal = tf.linalg.diag([1,2,3])
m_transpose = tf.linalg.matrix_transpose(m)
m_inverse = tf.linalg.inv(m)
m_multiplied = tf.matmul(m, m_inverse)
m_determinant = tf.linalg.det(m)
my_matrices = [m, m_diagonal, m_transpose, m_inverse, m_multiplied, m_determinant]
for mat in my_matrices:
    print(np.round(mat,3))
    print('\n')

[[1. 2.]
 [3. 4.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 3.]
 [2. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[1. 0.]
 [0. 1.]]


-2.0




In [16]:
# Initializing Variables #1
x = tf.Variable(initial_value=5, name='x')       # Define.
y = tf.Variable(initial_value=6, name='y')       # Define.
f = (x - y)*y + 3                                # Define.
print(f)

tf.Tensor(-3, shape=(), dtype=int32)


In [17]:
# Initializing Variables #2
x = tf.Variable(initial_value=3, name='x')       # Define.
y = tf.Variable(initial_value=2, name='y')       # Define.
f = x*y + y + 3                                  # Define.
print(f)

tf.Tensor(11, shape=(), dtype=int32)
